#!/bin/bash
source env_var #place your home directory here.
source slow_arrays
source slow_functions
## These are the usual results for my current setup.
# gpu=0000:03:00.0
# aud=0000:03:00.1
# gpu_id="0x1002 0x67df"
# aud_id="0x1002 0xaaf0"
# echo ${IDS[@]}
# echo ${DEVICES[@]}
# echo ${DRIVERS[@]}
# echo $IOMMU_GROUP
# Check if running sudo or as root for permissions.
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root or with sudo privileges."
  exit 1
fi

check_drivers() {
if [ ${#DRIVERS[@]} -gt 0 ]; then
    for driver in "${DRIVERS[@]}"; do
        current_driver=${driver##*/}
        echo "Current driver: $current_driver"
    done
    # Decide which script to call based on the results of the DRIVERS array
    if [[ " ${DRIVERS[*]} " == *"vfio_pci"* ]]; then
        echo "VFIO-PCI drivers found, running script for found vfio"
        vfio_found
    elif [[ " ${DRIVERS[*]} " == *"amdgpu"* ]]; then
        echo "AMDGPU drivers found, running script for found amdgpu"
        amdgpu_found
    else
        echo "No known drivers found, running off a cliff"
        rescan_pci
        vfio_found
        exit 1
    fi
    # if [ ${#DRIVERS[@]}  1 ]; then
    #     echo "Only one driver found, performing action for single driver"
    #     # Perform action for single driver
    # elif [ ${#DRIVERS[@]} -gt 1 ]; then
    #     unique_drivers=( "$(printf "%s\n" "${DRIVERS[@]}" | awk -F / '{print $NF}' | sort -u)" )
    #     if [ ${#unique_drivers[@]} -eq 1 ]; then
    #         echo "Multiple drivers found, but they are the same, performing action for same drivers"
    #         # Perform action for same drivers
    #         bash $HOME/.local/share/amdgpu-vfio/scripts/amdgpu_snd_hda_intel_add_new_id
    #     else
    #         echo "Multiple drivers found, and they are different, performing action for different drivers"
    #         # Perform action for different drivers
    #         bash $HOME/.local/share/amdgpu-vfio/scripts/vfio_add_new_id
    #     fi
    # fi
fi
}
check_drivers
exit 0
