#!/bin/bash
## ADDING FUNCTIONS
## Adds the IDs to the AMDGPU and SND_HDA_INTEL driver
add_amdgpu_snd_hda_intel() {
if [ ${#IDS[@]} -gt 0 ]; then
    for id in "${IDS[@]}"; do
        read -r manufacturer_id component_id <<< "$id"
        echo "Adding GPU/AUD ID $manufacturer_id $component_id to AMDGPU/SND_HDA_INTEL driver"
        if [[ $manufacturer_id == "0x1002" ]]; then
            if [[ $component_id == "0x67df" ]]; then
                # Perform action for 0x1002 0x67df
                echo "$manufacturer_id $component_id" > /sys/bus/pci/drivers/amdgpu/new_id
                sleep 1
            elif [[ $component_id == "0xaaf0" ]]; then
                # Perform action for 0x1002 0xaaf0
                echo "$manufacturer_id $component_id" > /sys/bus/pci/drivers/snd_hda_intel/new_id
                sleep 1
            fi
        fi
    done
fi
}

## Adds the current IDs to the VFIO-PCI driver
add_vfio_pci() {
if [ ${#IDS[@]} -gt 0 ]; then
    for id in "${IDS[@]}"; do
        echo "Addind new ID $id to VFIO-PCI driver"
        # echo "$id" > /sys/bus/pci/drivers/vfio-pci/new_id
        sleep 2
    done
fi
}
## REMOVING FUNCTIONS
## Removes the IDs to the AMDGPU and SND_HDA_INTEL driver
remove_amdgpu_snd_hda_intel() {
if [ ${#IDS[@]} -gt 0 ]; then
    for id in "${IDS[@]}"; do
        read -r manufacturer_id component_id <<< "$id"
        if [[ $manufacturer_id == "0x1002" ]]; then
            if [[ $component_id == "0x67df" ]]; then
                # Perform action for 0x1002 0x67df
                echo "Removing GPU ID $manufacturer_id $component_id to AMDGPU driver"
                # echo "$manufacturer_id $component_id" > /sys/bus/pci/drivers/amdgpu/remove_id
                sleep 1
            elif [[ $component_id == "0xaaf0" ]]; then
                # Perform action for 0x1002 0xaaf0
                echo "Removing AUD ID $manufacturer_id $component_id to SND_HDA_INTEL driver"
                # echo "$manufacturer_id $component_id" > /sys/bus/pci/drivers/snd_hda_intel/remove_id
                sleep 1
            fi
        fi
    done
fi
}
## Removes the current IDs from the VFIO-PCI driver
remove_vfio_pci() {
if [ ${#IDS[@]} -gt 0 ]; then
    for id in "${IDS[@]}"; do
        echo "Removing GPU/AUD ID $id from VFIO-PCI driver"
        # echo "$id" > /sys/bus/pci/drivers/vfio-pci/remove_id
        sleep 2
    done
fi
}
## RESCANand REMOVE DEVICES FROM PCI BUS
# Remove the devices from the PCI bus, and then rescan to attach the chosen drivers
remove_pci() {
if [ ${#DEVICES[@]} -gt 0 ]; then
    for device in "${DEVICES[@]}"; do
        if [ -f /sys/bus/pci/devices/$device/remove ]; then
            echo "Removing device $device from PCI bus"
            # echo "1" > /sys/bus/pci/devices/$device/remove
            sleep 2
        fi
    done
fi
}
# Rescan the PCI bus
rescan_pci() {
echo "Rescanning the PCI bus to reattach to original drivers"
echo "1" > /sys/bus/pci/rescan
}
echo "GPU Passthrough Switch Code Sourced Properly!"

# Script Call Functions
# amdgpu_snd_hda_intel_add_new_id

amdgpu_found(){
## Removes the IDs to the AMDGPU and SND_HDA_INTEL driver
## There may be a chance that this is needed for multi GPU set ups
## Or if you use nVIDIA drivers. but with my tests they were 
## Just producing write error: File Exists.
# remove_amdgpu_snd_hda_intel
sleep 5
## Adds the current IDs to the VFIO-PCI driver
add_vfio_pci
sleep 5
## Removes the devices from the PCI bus and then re-scans to allow complete connection
remove_pci
sleep 5
rescan_pci
}

vfio_found(){
## Removes the current IDs from the VFIO-PCI driver
remove_vfio_pci
sleep 5
## Adds the IDs to the AMDGPU and SND_HDA_INTEL driver
## There may be a chance that this is needed for multi GPU set ups
## Or if you use nVIDIA drivers. but with my tests they were 
## Just producing write error: File Exists.
#add_amdgpu_snd_hda_intel
sleep 5
## Removes the devices from the PCI bus and then re-scans to allow complete connection
remove_pci
sleep 5
rescan_pci
}